# DSE5002 Module 1 Pair Programming 

# Ryan Waterman, March 2025

# Intro to some Python Ideas

Basic Variables

Python is dynamically typed, like R, so Python decides how to store variables when you declare them.

Python has floating points,  integers, complex numbers, boolean and strings as the basic type elements

It does not have a factor like R does

The basic math operations work the same way they do in R

In [5]:
a=5
b=5
print(a+b)

10


In [6]:
#We can use the type function to see what type of variable on object is
type(a)

int

In [7]:
a=5.0
type(a)

float

# Question

Why is a an integer in one case and a float in the other?

# The variable is an integer in one case, and a float in the other because decimals are seen as 'floating point values' to the python interpreter.

In [8]:
a="5"
type(a)

str

Storage classes in Python,  such as str and more complex types have built in member functions that operate on items in the class


The dir() function will show the variables in the class, which have underscores added, and functions which do not

In [14]:
dir(a)


['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

Looking at a string, there is along list of available functions

We'll define a more interesting string and see what some of these functions do.

Notice how the member functions are called, as the variable name, a period and then the function name and parenthesis

Not all functions in Python are member functions, this is just showing how to call member functions once you find them using
dir()

In [7]:
a="Joe chased a leaf,"
print(a.upper())
print(a.lower())
print(a.title())

JOE CHASED A LEAF,
joe chased a leaf,
Joe Chased A Leaf,


In [8]:
a.split()

['Joe', 'chased', 'a', 'leaf,']

The key idea here is that dir() can show you a bunch of useful functions available

In [10]:
a.__len__

<method-wrapper '__len__' of str object at 0x000002623D8AAE90>

In [15]:
#this is an iPython "magic" command to see the user defined variables in use at the moment
# it is a lift from the Matlab system
# "magic" commands are utility commands in iPython or Jupyter, not part of python

test1=1

%who

a	 b	 test	 test1	 


In [16]:
%whos

Variable   Type    Data/Info
----------------------------
a          str     Hello    World
b          int     5
test       str     Hello    World
test1      int     1


To see more about magic commands, see

https://ipython.readthedocs.io/en/stable/interactive/magics.html



Thee are 4 types of built-in data structures in basic python

list, tuple, dictionary and set

We'll talk about them next week

#Numpy

Numpy stands for numerical python,   it has array and vector data types defined within it

To create matrices and do matric operations in Python,  people typically use Numpy

Many other structures and common python packages are built on top of numpy classes

To use Numpy, we have to import the package.   Note that the package must already be installed in your environment

np is the classic appreciation or alias for numpy

In [18]:
import numpy as np

Numpy matrices 

-must all have the same type of element

- are indexed by the row and column number

-but like most other language, the first row is 0, and the first column is also 0
    with R indices start with 1,  in python they start with 0
    
-think of the indices in python as the distance from the start of an array or matrix

In [19]:
x=np.matrix('1 2 3; 4 5 6; 7 8 9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
x[1,0]

np.int64(4)

# Action/Question

What is the index of the "8" in this matrix? 

# The index of 8 is [2,1]

Test your answere

In [24]:
x[2,1]

np.int64(8)

In [25]:
type(x)

numpy.matrix

In [26]:
# dtype is an attribute of a numpy array that indicates the type of elements in the matrix

x.dtype

dtype('int64')

In [27]:
x.size

9

In [28]:
x.shape

(3, 3)

In [29]:
dir(x)

['A',
 'A1',
 'H',
 'I',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__

# Action

Add a cell and try some different operations from the member functions,  see what they do

In [31]:
print(x.T)
print(x.transpose())
print(x.reshape(1, 9))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3 4 5 6 7 8 9]]


Specialized Matrices

In [32]:
x=np.identity(6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
x=np.ones((4,5))
print(x)
x.dtype

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


dtype('float64')

In [36]:
x=np.zeros((3,6))
print(x)
x.dtype

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


dtype('float64')

To learn more about using Numpy to do linear algebra see:

https://numpy.org/doc/stable/user/absolute_beginners.html

Another option is

https://www.kaggle.com/code/legendadnan/numpy-tutorial-for-beginners-data-science

#Pandas

Pandas is a libary that implies a data frame,  much like the dataframes in R, or a data table in SQL

Each row is an observation,   each column is a variable.

The columns are actually 1 dimensional numpy arrays (ie n x 1 matrics, for n rows)

There are an immense number of member functions to let us carry out operations on Pandas dataframes

Slicing, sorting and selecting work much like they do in R

We typically import pandas as pd

In [1]:
import pandas as pd

In [38]:
#edit this line so it contains the full path name for the Boston Asssessment_Roll_2024.cvs


infile="Boston_Assessment_Roll_2024.csv"

In [39]:
#import the file,  place it into a Pandas dataframe

Boston_roll=pd.read_csv(infile)

C:\Users\water\AppData\Local\Temp\ipykernel_9536\3031399445.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  Boston_roll=pd.read_csv(infile)


In [40]:
# We have a head function, just as in R

Boston_roll.head(5)

_id        PID  CM_ID     GIS_ID  ST_NUM       ST_NAME UNIT_NUM  \
0    1  100001000    NaN  100001000   104.0     PUTNAM ST      NaN   
1    2  100002000    NaN  100002000   197.0  Lexington ST      NaN   
2    3  100003000    NaN  100003000   199.0  Lexington ST      NaN   
3    4  100004000    NaN  100004000   201.0  Lexington ST      NaN   
4    5  100005000    NaN  100005000   203.0  Lexington ST      NaN   

          CITY  ZIP_CODE  BLDG_SEQ  ...     KITCHEN_STYLE2   KITCHEN_STYLE3  \
0  EAST BOSTON    2128.0         1  ...    S - Semi-Modern  S - Semi-Modern   
1  EAST BOSTON    2128.0         1  ...         M - Modern       M - Modern   
2  EAST BOSTON    2128.0         1  ...    S - Semi-Modern  S - Semi-Modern   
3  EAST BOSTON    2128.0         1  ...    S - Semi-Modern  S - Semi-Modern   
4  EAST BOSTON    2128.0         1  ...  N - No Remodeling              NaN   

            HEAT_TYPE HEAT_SYSTEM         AC_TYPE FIREPLACES ORIENTATION  \
0  W - Ht Water/Steam         NaN        N - None        0.0         NaN   
1  F - Forced Hot Air         NaN  C - Central AC        0.0         NaN   
2      S - Space Heat         NaN        N - None        0.0         NaN   
3  W - Ht Water/Steam         NaN        N - None        0.0         NaN   
4  W - Ht Water/Steam         NaN        N - None        0.0         NaN   

  NUM_PARKING    PROP_VIEW CORNER_UNIT  
0         3.0  A - Average         NaN  
1         0.0  A - Average         NaN  
2         0.0  A - Average         NaN  
3         0.0  A - Average         NaN  
4         0.0  A - Average         NaN  

[5 rows x 66 columns]

In [45]:
#We can access columns by name, rowns by number
# Notice that 0:5 gives us all values from 0 to 4,  5 is not included

print(Boston_roll["CITY"][0:5])
print(Boston_roll["ZIP_CODE"][0:5])

0    EAST BOSTON
1    EAST BOSTON
2    EAST BOSTON
3    EAST BOSTON
4    EAST BOSTON
Name: CITY, dtype: object
0    2128.0
1    2128.0
2    2128.0
3    2128.0
4    2128.0
Name: ZIP_CODE, dtype: float64


In [48]:
# we can index using two numbers, note the need to use the .iloc notation to do this

Boston_roll.iloc[5:10,7]

5    EAST BOSTON
6    EAST BOSTON
7    EAST BOSTON
8    EAST BOSTON
9    EAST BOSTON
Name: CITY, dtype: object

In [49]:
#let's look at the member functions

dir(Boston_roll)

['AC_TYPE',
 'BDRM_COND',
 'BED_RMS',
 'BLDG_SEQ',
 'BLDG_TYPE',
 'BLDG_VALUE',
 'BTHRM_STYLE1',
 'BTHRM_STYLE2',
 'BTHRM_STYLE3',
 'CD_FLOOR',
 'CITY',
 'CM_ID',
 'COM_UNITS',
 'CORNER_UNIT',
 'EXT_COND',
 'EXT_FNISHED',
 'FIREPLACES',
 'FULL_BTH',
 'GIS_ID',
 'GROSS_AREA',
 'GROSS_TAX',
 'HEAT_SYSTEM',
 'HEAT_TYPE',
 'HLF_BTH',
 'INT_COND',
 'INT_WALL',
 'KITCHENS',
 'KITCHEN_STYLE1',
 'KITCHEN_STYLE2',
 'KITCHEN_STYLE3',
 'KITCHEN_TYPE',
 'LAND_SF',
 'LAND_VALUE',
 'LIVING_AREA',
 'LU',
 'LUC',
 'LU_DESC',
 'MAIL_ADDRESSEE',
 'MAIL_CITY',
 'MAIL_STATE',
 'MAIL_STREET_ADDRESS',
 'MAIL_ZIP_CODE',
 'NUM_BLDGS',
 'NUM_PARKING',
 'ORIENTATION',
 'OVERALL_COND',
 'OWNER',
 'OWN_OCC',
 'PID',
 'PROP_VIEW',
 'RC_UNITS',
 'RES_FLOOR',
 'RES_UNITS',
 'ROOF_COVER',
 'ROOF_STRUCTURE',
 'SFYI_VALUE',
 'STRUCTURE_CLASS',
 'ST_NAME',
 'ST_NUM',
 'T',
 'TOTAL_VALUE',
 'TT_RMS',
 'UNIT_NUM',
 'YR_BUILT',
 'YR_REMODEL',
 'ZIP_CODE',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_T

Just a few options, eh?

Pandas can do a lot of different things....

We will see a lot more of Pandas later

If you want to work ahead a bit

https://www.kaggle.com/learn/pandas

https://pandas.pydata.org/docs/getting_started/tutorials.html
